spring:
  data:
    mongodb:
      uri: mongodb+srv://mentovia8:ucvF9TVI8hxMIFWg@cluster0.xqtv8ip.mongodb.net/mentovia?retryWrites=true&w=majority
      database: mentovia
  security:
    jwt:
      secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 86400000

server:
  port: 8081
  servlet:
    context-path: /api

# File upload configuration
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB



# ── ADD these lines to define your file-storage directories ────────────────────
file:
  upload-dir: uploads        # root folder
  pdf-dir: "${file.upload-dir}/pdfs"
  video-dir: "${file.upload-dir}/videos"

# Logging configuration
logging:
  level:
    root: INFO
    com.skillsharing: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
